### ISSUE TITLE
Not able to boot on iCub image 6

### ISSUE THREAD

**Issue by ahoarau** [robotology/icub-support#255]
##### Description of the failure

The iCub 6 seems to be built for an x64 CPU :  
```
This kernel requires x86_64 cpu, but only detected an i686 cpu, unable to boot. 
Please use a kernel appropriate for your CPU
```

##### Detailed conditions when the failure occurred

Thanks to your tuto on issue https://github.com/robotology/icub-support/issues/152 (I think the issue is the same btw ), @jeljaik and I managed to plug a monitor on Paris01 pc104.

We'll try later with icub image 5, but i'm pretty sure it'll be the same error.

**Comment by jeljaik** [comment]
As suspected by @ahoarau we have the same problem with image 5.0 on `iCubParis01`. The exact message when booting is: 

```bash
Loading /live/vmlinuz.....
Loading /live/initrd.img...............ready
This kernel requires an x86-64 CPU, but only detected an i686 CPU. 
Unable to boot - please use a kernel appropriate for your CPU
```

**Comment by jeljaik** [comment]
@mbrunettini Can you help us please?

**Comment by mbrunettini** [comment]
Latest images are built only for x64 processors.

**Comment by jeljaik** [comment]
iCubParis01: 002-03-04-04-04
iCubParis02: Not sure where to find it. @rlober do you?

**Comment by rlober** [comment]
@jeljaik No idea. I am guessing it is on pc104

**Comment by jeljaik** [comment]
On iCubParis01 it is as seen in this picture:  
iCubParis02 does not have it though ...

![image](https://cloud.githubusercontent.com/assets/5030039/16043561/830b19d0-3240-11e6-892d-297325428634.jpg)

**Comment by rlober** [comment]
@jeljaik That is because iCubParis02 is cursed.

**Comment by jeljaik** [comment]
@mbrunettini Should we assume that the conclusion is to stick to the 4.0 image forever and ever?

**Comment by jeljaik** [comment]
If that is the case, then there's something really wrong going on here, because in [these](http://wiki.icub.org/wiki/How_to_burn_Linux_pc104_image_(version_prev._5.0)) for < 5.0 images, the link takes us to this: 

<img width="598" alt="screen shot 2016-06-15 at 10 59 16" src="https://cloud.githubusercontent.com/assets/5030039/16073867/37b40246-32e8-11e6-8fce-b32b63258691.png">

Where clearly there's no < 5.0 image.

😟 ❓:question:

**Comment by jeljaik** [comment]
Thanks for the 4.0 images! I just saw they've been added.

**Comment by jeljaik** [comment]
So, we successfully managed to boot with Image 4.0, **but only with the static one**. We couldn't get the **dhcp** image   [here](http://www.icub.org/download/pc104-images/) to boot. We tried both EXT4 and FAT32 formats and checked with `md5sum` the uncompressed files. We also made sure to use the `DEVICE_NODE` rather than the partition. Still, the `dhcp` image shows the following message when connecting a monitor to `pc104`.

![img_2016-06-16 11 36 15 jpg](https://cloud.githubusercontent.com/assets/5030039/16114610/6d2a3514-33c2-11e6-8f80-8b51d9cf7267.jpg)

**Comment by lornat75** [comment]
iCubParis01 mounts the old can bus interface with requires images 1.8 (which have been restored in http://www.icub.org/download/pc104-images/). It is not only a problem of architecture (32 bits): the can bus driver is available only for the Linux kernel version shipped with images 1.8. More recent versions may boot, but will not load the can bus driver.

iCubParis02 on the other hand should work with images 6.0.

**Comment by jeljaik** [comment]
Thanks @lornat75 It's now clear. We'll proceed accordingly.

**Comment by jeljaik** [comment]
Hello @lornat75 . We went back to the 1.8 image but with the latest `yarp` we get the following when compiling on PC104

```
/usr/local/src/robot/source/yarp/src/libYARP_OS/src/BottleImpl.cpp: In member function 'virtual void yarp::os::impl::StoreInt64::fromString(const yarp::os::ConstString&)':
/usr/local/src/robot/source/yarp/src/libYARP_OS/src/BottleImpl.cpp:722: error: 'strtoll' is not a member of 'ACE_OS'
make[2]: *** [src/libYARP_OS/CMakeFiles/YARP_OS.dir/src/BottleImpl.cpp.o] Error 1
make[1]: *** [src/libYARP_OS/CMakeFiles/YARP_OS.dir/all] Error 2
make: *** [all] Error 2
```

On PC104
```
icub@pc104:~$ dpkg -l | grep libace
ii  libace-dev                              5.4.7-12                             C++ network programming framework developmen
ii  libace5.4.7c2a                          5.4.7-12                             C++ network programming framework
```

**Comment by jeljaik** [comment]
Ref: https://github.com/robotology/yarp/issues/807

**Comment by julijenv** [comment]
Hi @jeljaik , I think you can close it no? :D

**Comment by jeljaik** [comment]
Oops, yes. Had closed only the referenced issue robotology/yarp#807
